### ISSUE TITLE
html strings with multiple tags

### ISSUE THREAD

**Issue by chiplay** [TimBeyer/html-to-vdom#4]
Hey @TimBeyer.  Thanks for your work on this awesome library - excited to give it a shot while experimenting converting our Backbone/Marionette app to use vdom / FRP under the hood.  My goal is to still use our current templates (jade->html) that we import into our views using a text module importer, and then parse them into vtrees using your library, before turning them into a vtree stream (see https://github.com/staltz/cycle)

My first roadblock has come here: `return htmlparserToVdom.convertTag(tags[0]);` as our templates all contain more then one tag.  I'm hoping to avoid adding boiler plate to all our views to wrap template code in an extra `div` to ensure only one root tag is returned from the parser, and I'm curious if you given any thought to that problem?

Thanks again!

**Comment by TimBeyer** [comment]
Hey @chiplay, probably it's too late already but you might be happy to hear that as of https://github.com/TimBeyer/html-to-vdom/releases/tag/v0.6.0 I implemented conversion of sibling nodes without enclosing tags.  
This now returns an array of VNodes.
